import importlib.util
import logging
import unittest
from pathlib import Path


_ADAPTER_PATH = Path(__file__).resolve().parents[1] / "alphazero_adapter.py"
_SPEC = importlib.util.spec_from_file_location("alphazero_adapter_module", _ADAPTER_PATH)
alphazero_adapter = importlib.util.module_from_spec(_SPEC)
assert _SPEC.loader is not None
_SPEC.loader.exec_module(alphazero_adapter)


class AdapterIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        alphazero_adapter._ensure_submodule_on_syspath()
        logger = logging.getLogger("alphazero-adapter-integration")
        logger.handlers = [logging.NullHandler()]
        cls.runtime = alphazero_adapter._build_runtime(simulation_num=32, logger=logger)

    def _assert_response_in_expected(self, request, expected_positions):
        response = alphazero_adapter._process_request(self.runtime, request)
        self.assertIsNotNone(response)
        actual = (response["rowIndex"], response["columnIndex"])
        self.assertIn(actual, expected_positions)

    def test_basic_game_patterns(self):
        patterns = [
            {
                "name": "opening_prefers_center",
                # empty board
                "request": {"command": "NEXT_BLACK", "chessboard": ""},
                "expected_positions": {(7, 7)},
            },
            {
                "name": "early_cross_shape_extension",
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # .......BW......
                # .......BW......
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                "request": {
                    "command": "NEXT_BLACK",
                    "chessboard": "B[77];W[78];B[87];W[88]",
                },
                "expected_positions": {(9, 8)},
            },
            {
                "name": "black_finishes_horizontal_five",
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ......WWW......
                # .......BBBB....
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                "request": {
                    "command": "NEXT_BLACK",
                    "chessboard": "B[77];W[66];B[78];W[67];B[79];W[68];B[7a]",
                },
                "expected_positions": {(7, 6), (7, 11)},
            },
            {
                "name": "black_finishes_diagonal_five",
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ......WWW......
                # .......B.......
                # ........B......
                # .........B.....
                # ..........B....
                # ...............
                # ...............
                # ...............
                # ...............
                "request": {
                    "command": "NEXT_BLACK",
                    "chessboard": "B[77];W[66];B[88];W[67];B[99];W[68];B[aa]",
                },
                "expected_positions": {(6, 6), (11, 11)},
            },
            {
                "name": "white_blocks_black_open_four",
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # BBBB...........
                # WWW............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                # ...............
                "request": {
                    "command": "NEXT_WHITE",
                    "chessboard": "B[70];W[80];B[71];W[81];B[72];W[82];B[73]",
                },
                "expected_positions": {(7, 4)},
            },
        ]

        for pattern in patterns:
            with self.subTest(pattern=pattern["name"]):
                self._assert_response_in_expected(
                    request=pattern["request"],
                    expected_positions=pattern["expected_positions"],
                )


if __name__ == "__main__":
    unittest.main()
